import { PrismaClient } from '../generated/prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import 'dotenv/config';
const adapter = new PrismaPg({
  connectionString: process.env.DATABASE_URL,
});
const prisma = new PrismaClient({
  adapter,
});

// export async function fases() {
//   await prisma.fases.createMany({
//     data: [
//       {
//         des_fase: 'Idea en proceso de validación',
//         logo_fase: '/logos/inicial.png',
//         id_fasex: 'Inicial',
//       },
//       {
//         des_fase: 'Negocio en funcionamiento básico',
//         logo_fase: '/logos/basico.png',
//         id_fasex: 'Básico',
//       },
//       {
//         des_fase: 'Empresa con estructura organizada',
//         logo_fase: '/logos/intermedio.png',
//         id_fasex: 'Intermedio',
//       },
//       {
//         des_fase: 'Modelo de negocio estable',
//         logo_fase: '/logos/satisfactorio.png',
//         id_fasex: 'Satisfactorio',
//       },
//       {
//         des_fase: 'Empresa consolidada',
//         logo_fase: '/logos/avanzado.png',
//         id_fasex: 'Avanzado',
//       },
//       {
//         des_fase: 'Empresa líder y sostenible',
//         logo_fase: '/logos/ideal.png',
//         id_fasex: 'Ideal',
//       },
//     ],
//     skipDuplicates: true,
//   });
// }

// fases()

// export async function municipios() {
//   await prisma.municipios.createMany({
//     data: [
//       { cod_munic: 13001, departamento: 'BOLIVAR', zona: 'NORTE', municipio: 'CARTAGENA' },
//       { cod_munic: 13006, departamento: 'BOLIVAR', zona: 'SUR', municipio: 'ACHI' },
//       { cod_munic: 13030, departamento: 'BOLIVAR', zona: 'SUR', municipio: 'ALTOS DEL ROSARIO' },
//       { cod_munic: 13042, departamento: 'BOLIVAR', zona: 'SUR', municipio: 'ARENAL' },
//       { cod_munic: 13052, departamento: 'BOLIVAR', zona: 'NORTE', municipio: 'ARJONA' },
//       { cod_munic: 13062, departamento: 'BOLIVAR', zona: 'NORTE', municipio: 'ARROYOHONDO' },
//       { cod_munic: 13074, departamento: 'BOLIVAR', zona: 'SUR', municipio: 'BARRANCO DE LOBA' },
//       { cod_munic: 13140, departamento: 'BOLIVAR', zona: 'NORTE', municipio: 'CALAMAR' },
//       { cod_munic: 13160, departamento: 'BOLIVAR', zona: 'SUR', municipio: 'CANTAGALLO' },
//       { cod_munic: 13188, departamento: 'BOLIVAR', zona: 'SUR', municipio: 'CICUCO' },
//       { cod_munic: 13212, departamento: 'BOLIVAR', zona: 'SUR', municipio: 'CORDOBA' },
//       { cod_munic: 13222, departamento: 'BOLIVAR', zona: 'NORTE', municipio: 'CLEMENCIA' },
//       {
//         cod_munic: 13244,
//         departamento: 'BOLIVAR',
//         zona: 'CENTRO',
//         municipio: 'EL CARMEN DE BOLIVAR',
//       },
//       { cod_munic: 13248, departamento: 'BOLIVAR', zona: 'CENTRO', municipio: 'EL GUAMO' },
//       { cod_munic: 13268, departamento: 'BOLIVAR', zona: 'SUR', municipio: 'EL PEÑON' },
//       { cod_munic: 13300, departamento: 'BOLIVAR', zona: 'SUR', municipio: 'HATILLO DE LOBA' },
//       { cod_munic: 13430, departamento: 'BOLIVAR', zona: 'SUR', municipio: 'MAGANGUE' },
//       { cod_munic: 13433, departamento: 'BOLIVAR', zona: 'NORTE', municipio: 'MAHATES' },
//       { cod_munic: 13440, departamento: 'BOLIVAR', zona: 'SUR', municipio: 'MARGARITA' },
//       { cod_munic: 13442, departamento: 'BOLIVAR', zona: 'CENTRO', municipio: 'MARIA LA BAJA' },
//       { cod_munic: 13458, departamento: 'BOLIVAR', zona: 'NORTE', municipio: 'MONTECRISTO' },
//       { cod_munic: 13468, departamento: 'BOLIVAR', zona: 'SUR', municipio: 'MOMPOS' },
//       { cod_munic: 13473, departamento: 'BOLIVAR', zona: 'SUR', municipio: 'MORALES' },
//       { cod_munic: 13490, departamento: 'BOLIVAR', zona: 'SUR', municipio: 'NOROSI' },
//       { cod_munic: 13549, departamento: 'BOLIVAR', zona: 'SUR', municipio: 'PINILLOS' },
//       { cod_munic: 13580, departamento: 'BOLIVAR', zona: 'SUR', municipio: 'REGIDOR' },
//       { cod_munic: 13600, departamento: 'BOLIVAR', zona: 'SUR', municipio: 'RIO VIEJO' },
//       { cod_munic: 13620, departamento: 'BOLIVAR', zona: 'NORTE', municipio: 'SAN CRISTOBAL' },
//       { cod_munic: 13647, departamento: 'BOLIVAR', zona: 'NORTE', municipio: 'SAN ESTANISLAO' },
//       { cod_munic: 13650, departamento: 'BOLIVAR', zona: 'SUR', municipio: 'SAN FERNANDO' },
//       { cod_munic: 13654, departamento: 'BOLIVAR', zona: 'CENTRO', municipio: 'SAN JACINTO' },
//       {
//         cod_munic: 13655,
//         departamento: 'BOLIVAR',
//         zona: 'CENTRO',
//         municipio: 'SAN JACINTO DEL CAUCA',
//       },
//       {
//         cod_munic: 13657,
//         departamento: 'BOLIVAR',
//         zona: 'CENTRO',
//         municipio: 'SAN JUAN NEPOMUCENO',
//       },
//       { cod_munic: 13667, departamento: 'BOLIVAR', zona: 'SUR', municipio: 'SAN MARTIN DE LOBA' },
//       { cod_munic: 13670, departamento: 'BOLIVAR', zona: 'SUR', municipio: 'SAN PABLO' },
//       { cod_munic: 13673, departamento: 'BOLIVAR', zona: 'NORTE', municipio: 'SANTA CATALINA' },
//       { cod_munic: 13683, departamento: 'BOLIVAR', zona: 'NORTE', municipio: 'SANTA ROSA' },
//       { cod_munic: 13688, departamento: 'BOLIVAR', zona: 'SUR', municipio: 'SANTA ROSA DEL SUR' },
//       { cod_munic: 13744, departamento: 'BOLIVAR', zona: 'SUR', municipio: 'SIMITI' },
//       { cod_munic: 13760, departamento: 'BOLIVAR', zona: 'NORTE', municipio: 'SOPLAVIENTO' },
//       { cod_munic: 13780, departamento: 'BOLIVAR', zona: 'SUR', municipio: 'TALAIGUA NUEVO' },
//       { cod_munic: 13810, departamento: 'BOLIVAR', zona: 'SUR', municipio: 'TIQUISIO' },
//       { cod_munic: 13836, departamento: 'BOLIVAR', zona: 'NORTE', municipio: 'TURBACO' },
//       { cod_munic: 13838, departamento: 'BOLIVAR', zona: 'NORTE', municipio: 'TURBANA' },
//       { cod_munic: 13873, departamento: 'BOLIVAR', zona: 'NORTE', municipio: 'VILLANUEVA' },
//       { cod_munic: 13894, departamento: 'BOLIVAR', zona: 'NORTE', municipio: 'ZAMBRANO' },
//     ],
//     skipDuplicates: true, // Opcional: evita errores si algún registro ya existe
//   });
// }

// municipios()

// export async function grupos() {
//   await prisma.grupos.createMany({
//     data: [
//       {
//         actividad:
//           'BioProductos: Son aquellos que, en su proceso de aprovechamiento, producción, manejo, transformación, comercialización y/o disposición, incorporan mejores prácticas ambientales, garantizando la conservación del medio de donde fueron extraídos y la sostenibilidad del recurso.',
//         logo_grupo: 'Grupos_Images/BioProductos.LogoGrupo.161931.png',
//       },
//       {
//         actividad:
//           'EcoProductos: Son todos aquellos bienes que pueden demostrar que en su proceso productivo, resultan ser menos contaminantes al medio, respeto a otros productos de su segmento; o que por las características intrínsecas del producto, de su utilización o de su proceso productivo, generan beneficios al ambiente. (Adoptado del PENMV, 2002) Incluye aprovechamiento y valoración de residuos, fuentes de energías sostenibles, construcciones sostenibles.',
//         logo_grupo: 'Grupos_Images/EcoIndustriales.LogoGrupo.162020.png',
//       },
//       {
//         actividad: 'Accion Climatica: Accion Climatica',
//         logo_grupo: 'Grupos_Images/Accion Climatica.LogoGrupo.162041.png',
//       },
//       {
//         actividad: 'EcoTurismo: eco turismo',
//         logo_grupo: 'Grupos_Images/EcoTurismo.LogoGrupo.162049.png',
//       },
//       {
//         actividad: 'Bienes y Servicios: Bienes y servicios',
//         logo_grupo: 'Grupos_Images/Bienes y Servicios.LogoGrupo.183244.png',
//       },
//     ],
//     skipDuplicates: true,
//   });
// }

// grupos()

// export async function dir_verde() {
//   await prisma.dir_verde.createMany({
//     data: [
//       {
//         negocio: 'Colinas Verdes',
//         id_grupo: 2,
//         sub_categoria: 'TURISMO SOSTENIBLE',
//         descripcion:
//           'Actividad económica que ofrece servicio de agro eco turismo y experiencias con la naturaleza.',
//         actividad: 'Agroecoturismo y conservación',
//         unidad_productiva: 'Hospedaje y senderismo',
//         direccion: 'Turbana, Bolívar, Colombia',
//         logo: 'DirVerde_Images/1.Logo.162457.jpg',
//         url_youtube: 'https://www.youtube.com/watch?v=4lIaROdi8fU',
//         url_facebook:
//           'https://www.facebook.com/p/Asociaci%C3%B3n-Agroecoturistica-Colinas-Verdes-100054525141567/',
//         url_instagram: 'https://www.instagram.com/asomupor/',
//         url_tiktok: 'https://tiktok.com/es',
//         url_negocio: 'https://wa.link/5oxdub',
//         pos_gps: '-75.4342491,10.298357',
//         id_fase: 1,
//         estado: 'Activo',
//         id_municipio: 13001,
//       },
//       {
//         negocio: 'Eco Hotel- Campo Verde',
//         id_grupo: 2,
//         sub_categoria: 'TURISMO SOSTENIBLE',
//         descripcion: 'Eco Hotel dedicado al turismo de naturaleza étnico y cultural.',
//         actividad: 'Turismo de naturaleza',
//         direccion: 'Isla Grande, Bolívar',
//         logo: 'DirVerde_Images/2.Logo.230028.png',
//         url_facebook: 'https://www.facebook.com/profile.php?id=100090779631989',
//         pos_gps: '-75.7313615,10.179568',
//         id_fase: 1,
//         estado: 'Activo',
//         id_municipio: 13001,
//       },
//       {
//         negocio: 'Cocotera Beach',
//         id_grupo: 2,
//         sub_categoria: 'TURISMO SOSTENIBLE',
//         descripcion:
//           'Establecimiento dedicado al turismo ecológico y experiencias de playa sostenibles.',
//         actividad: 'Turismo ecológico',
//         direccion: 'Isla Grande, Bolívar',
//         logo: 'DirVerde_Images/3.Logo.162550.jpg',
//         url_facebook: 'https://www.facebook.com/p/Cocotera-Beach-100094159034888/',
//         url_negocio: 'https://cocoterabeach.com/',
//         pos_gps: '-75.7409857,10.1800583',
//         id_fase: 1,
//         estado: 'Activo',
//         id_municipio: 13001,
//       },
//       {
//         negocio: 'AsoAgrapat',
//         id_grupo: 2,
//         sub_categoria: 'AGROINDUSTRIA SOSTENIBLE',
//         descripcion:
//           'Asociación agroempresarial de la vereda nueva Pativaca dedicada a productos derivados de la papaya.',
//         actividad: 'Transformación de frutas (Papaya)',
//         unidad_productiva: 'Mermeladas y dulces típicos artesanales',
//         direccion: 'Vereda Nueva Pativacoa, El Salado, Carmen de Bolívar',
//         logo: 'DirVerde_Images/4.Logo.020623.jpg',
//         pos_gps: null,
//         id_fase: 1,
//         estado: 'Activo',
//         id_municipio: 13001,
//       },
//       {
//         negocio: 'Job Creaciones',
//         id_grupo: 2,
//         sub_categoria: 'APROVECHAMIENTO Y VALORACIÓN DE RESIDUOS',
//         descripcion:
//           'Fabricación de maquetas y artículos decorativos mediante la transformación de materiales reciclados.',
//         actividad: 'Artesanías en material reciclado',
//         direccion: 'Barrio Soplaviento, Calle Antonio Santos',
//         representante: 'JOB CAPRASIA',
//         url_youtube: 'https://www.youtube.com/@jobcaprasia2403',
//         a_o_verificacion: new Date('2022-02-01T00:00:00Z'),
//         pos_gps: null,
//         id_fase: 1,
//         estado: 'Activo',
//         id_municipio: 13001,
//       },
//       {
//         negocio: 'Amushi',
//         id_grupo: 2,
//         sub_categoria: 'AGROINDUSTRIA SOSTENIBLE',
//         descripcion:
//           'Productores de snacks derivados del ñame (Ñame Chips) cultivados de forma sostenible.',
//         actividad: 'Transformación de tubérculos',
//         unidad_productiva: 'Ñame Chips',
//         direccion: 'San Isidro, El Carmen de Bolívar',
//         representante: 'LUZMERY VALDEZ',
//         url_instagram: 'https://www.instagram.com/nami_chips/',
//         pos_gps: '-75.6095627,10.0560848',
//         a_o_verificacion: new Date('2021-01-01T00:00:00Z'),
//         id_fase: 1,
//         estado: 'Activo',
//         id_municipio: 13001,
//       },
//       {
//         negocio: 'F&M PERFUMES',
//         id_grupo: 2,
//         sub_categoria: 'APROVECHAMIENTO Y VALORACIÓN DE RESIDUOS',
//         descripcion:
//           'Producción de esencias y perfumes naturales con enfoque en equilibrio ambiental.',
//         actividad: 'Esencias y perfumes naturales',
//         direccion: 'Calle 26 46 25 Barrio Santander',
//         representante: 'PATRICIA BERROCAL',
//         url_facebook: 'https://www.facebook.com/profile.php?id=61554687242169',
//         pos_gps: '-61.0700973,23.5791365',
//         a_o_verificacion: new Date('2020-01-01T00:00:00Z'),
//         id_fase: 1,
//         estado: 'Activo',
//         id_municipio: 13001,
//       },
//       {
//         negocio: 'CAYUCO CAMPING BARÚ',
//         id_grupo: 2,
//         sub_categoria: 'TURISMO SOSTENIBLE',
//         descripcion:
//           'Servicio de alojamiento tipo camping con enfoque en recuperación y remediación ambiental.',
//         actividad: 'Alojamiento sostenible',
//         direccion: 'Vía Barú KM 11',
//         representante: 'DANIEL IGNACIO GALVIS',
//         logo: 'DirVerde_Images/10.Logo.020230.jpg',
//         pos_gps: '-75.5984227,10.3049568',
//         id_fase: 2,
//         estado: 'Activo',
//         id_municipio: 13001,
//       },
//       {
//         negocio: 'ECOTOUR BOQUILLA',
//         id_grupo: 2,
//         sub_categoria: 'TURISMO SOSTENIBLE',
//         descripcion:
//           'Turismo comunitario y ecoturismo con guianza personalizada en la zona de manglares.',
//         actividad: 'Ecoturismo comunitario',
//         direccion: 'La Boquilla, Sector Boca Natural',
//         representante: 'RONY MONSALVE',
//         url_negocio: 'https://ecotoursboquilla.com/',
//         pos_gps: '-75.490103,10.48674',
//         a_o_verificacion: new Date('2023-01-01T00:00:00Z'),
//         id_fase: 1,
//         estado: 'Activo',
//         id_municipio: 13001,
//       },
//       {
//         negocio: 'ECOBARÚ',
//         id_grupo: 2,
//         sub_categoria: 'APROVECHAMIENTO Y VALORACIÓN DE RESIDUOS',
//         descripcion:
//           'Empresa dedicada a la recuperación de residuos aprovechables y educación ambiental en zonas marinas.',
//         actividad: 'Gestión de residuos y recuperación de ecosistemas',
//         direccion: 'Vía Playa Blanca, Avenida Principal',
//         representante: 'MILTON LEANDRO OCAMPO PÉREZ',
//         url_instagram: 'https://www.instagram.com/ecobaructg/',
//         pos_gps: '-81.8501748,9.2588516',
//         id_fase: 1,
//         estado: 'Activo',
//         id_municipio: 13001,
//       },
//       {
//         negocio: 'CERRO MACO CAFÉ BAR S.A.S',
//         id_grupo: 2,
//         sub_categoria: 'AGROINDUSTRIA SOSTENIBLE',
//         descripcion: 'Procesos de producción artesanal de café y cacao orgánico de la región.',
//         actividad: 'Café y Cacao orgánico',
//         direccion: 'Cll. 22 #40',
//         representante: 'NEYL REYES ANILLOS',
//         url_instagram: 'https://www.instagram.com/cerromaco/',
//         pos_gps: '-77.561829,9.8291936',
//         id_fase: 1,
//         estado: 'Activo',
//         id_municipio: 13001,
//       },
//       {
//         negocio: 'ASOMUVICAS',
//         id_grupo: 2,
//         sub_categoria: 'AGROINDUSTRIA SOSTENIBLE',
//         descripcion:
//           'Asociación de mujeres víctimas del conflicto dedicadas al tejido tradicional en telar vertical.',
//         actividad: 'Artesanías y tejidos tradicionales',
//         unidad_productiva: 'Hamacas, bolsos y línea hogar',
//         direccion: 'CRA. 48 #28 04, San Jacinto',
//         representante: 'GLADYS ESTHER PÉREZ GARCÍA',
//         pos_gps: null,
//         id_fase: 1,
//         estado: 'Activo',
//         id_municipio: 13001,
//       },
//     ],
//     skipDuplicates: true,
//   });
// }

// dir_verde()

// export async function dir_verde_resto() {
//   await prisma.dir_verde.createMany({
//     data: [
//       {
//         negocio: 'LOGISTIC Y TRANSPORTE SEGURO SAMANEA',
//         id_grupo: 2,
//         sub_categoria: 'APROVECHAMIENTO Y VALORACIÓN DE RESIDUOS',
//         descripcion:
//           'Entidad dedicada a la recuperación de residuos aprovechables inorgánicos y aceite de cocina usado.',
//         actividad: 'Gestión de residuos inorgánicos y aceites',
//         direccion: 'Calle 11 de Noviembre 30 G 27 Escallon Villa',
//         representante: 'YANET CECILIA GUETO ALCALA',
//         logo: 'DirVerde_Images/13.Logo.213028.jpg',
//         url_facebook: 'https://www.facebook.com/samanea.ctg/',
//         url_instagram: 'https://www.instagram.com/samanea.bol/',
//         pos_gps: null,
//         id_fase: 1,
//         estado: 'Activo',
//         id_municipio: 13001,
//       },
//       {
//         negocio: 'CENTRO UBUNTU',
//         id_grupo: 2,
//         sub_categoria: 'TURISMO SOSTENIBLE',
//         descripcion:
//           'Centro de capacitación y alojamiento sostenible enfocado en servicios de turismo de naturaleza.',
//         actividad: 'Alojamiento y capacitaciones ambientales',
//         direccion: 'Isla Grande, Bolívar',
//         representante: 'MARGARITA OLARTE ZTHELIUS',
//         logo: 'DirVerde_Images/15.Logo.214901.jpg',
//         url_instagram: 'https://www.instagram.com/ubuntu.isla/',
//         pos_gps: '-75.7329438,10.1775337',
//         id_fase: 1,
//         estado: 'Activo',
//         id_municipio: 13001,
//       },
//       {
//         negocio: 'HOSTAL VISTAMAR',
//         id_grupo: 2,
//         sub_categoria: 'TURISMO SOSTENIBLE',
//         descripcion:
//           'Servicios de hostal y restaurante con enfoque en la conservación del entorno marino.',
//         actividad: 'Hostal y Restaurante ecológico',
//         direccion: 'Isla Grande, Bolívar',
//         representante: 'YESICA ESTHER FERRER AHUMADA',
//         logo: 'DirVerde_Images/16.Logo.215555.jpg',
//         url_instagram: 'https://www.instagram.com/vistaalmar_baru/',
//         pos_gps: '-75.7253812,10.1834655',
//         id_fase: 1,
//         estado: 'Activo',
//         id_municipio: 13001,
//       },
//       {
//         negocio: 'TORRES JIMENEZ Y AHUMEDO SAS',
//         id_grupo: 2,
//         sub_categoria: 'RESTAURACION',
//         descripcion:
//           'Diseño, construcción y mantenimiento de zonas verdes utilizando abonos orgánicos.',
//         actividad: 'Paisajismo y mantenimiento ambiental',
//         direccion: 'Pasacaballo, Sector Nuevo Porvenir Calle 10 # 19-45',
//         representante: 'EDWIN TORRES JIMENEZ',
//         logo: 'DirVerde_Images/17.Logo.220014.jpg',
//         pos_gps: '-75.5161446,10.2813699',
//         id_fase: 1,
//         estado: 'Activo',
//         id_municipio: 13001,
//       },
//       {
//         negocio: 'ECOZONORTE S.A.S',
//         id_grupo: 2,
//         sub_categoria: 'RESTAURACION',
//         descripcion: 'Vivero dedicado a la producción de plantas para restauración de ecosistemas.',
//         actividad: 'Producción de material vegetal (Vivero)',
//         direccion: 'Sector La Ceiba, Tierra Baja',
//         representante: 'RAFAEL SANCHEZ',
//         logo: 'DirVerde_Images/18.Logo.020740.jpg',
//         url_negocio: 'https://ecozonorte.com/',
//         pos_gps: '-75.4751075,10.4875867',
//         id_fase: 1,
//         estado: 'Activo',
//         id_municipio: 13001,
//       },
//       {
//         negocio: 'ASOCIACIÓN DE CAMPESINOS NUEVA ESPERANZA',
//         id_grupo: 2,
//         sub_categoria: 'AGROINDUSTRIA SOSTENIBLE',
//         descripcion: 'Producción y transformación de ajonjolí en cremas nutritivas artesanales.',
//         actividad: 'Transformación de ajonjolí',
//         direccion: 'Corregimiento de Guaymaral',
//         representante: 'YIMIS ISABEL SEVERICHE MONTES',
//         logo: 'DirVerde_Images/20.Logo.221219.png',
//         pos_gps: '-74.85,8.4333',
//         id_fase: 1,
//         estado: 'Activo',
//         id_municipio: 13001,
//       },
//       {
//         negocio: 'RISAS DEL SOL TOURS',
//         id_grupo: 2,
//         sub_categoria: 'TURISMO SOSTENIBLE',
//         descripcion: 'Ecoturismo comunitario centrado en la cultura y gastronomía local.',
//         actividad: 'Turismo comunitario y cultural',
//         direccion: 'CLL C 115-32 La Curva',
//         representante: 'SOL MILENA RODRIGUEZ JULIO',
//         logo: 'DirVerde_Images/22.Logo.020502.jpg',
//         url_tiktok: 'https://www.tiktok.com/@risasdelsoltours',
//         pos_gps: '-75.3015516,9.9817267',
//         id_fase: 1,
//         estado: 'Activo',
//         id_municipio: 13001,
//       },
//       {
//         negocio: 'ASOCIACIÓN MUJERES INNOVADORAS - YUCAR',
//         id_grupo: 2,
//         sub_categoria: 'AGROINDUSTRIA SOSTENIBLE',
//         descripcion: 'Elaboración artesanal de harina de yuca por mujeres rurales.',
//         actividad: 'Producción de harina de yuca',
//         direccion: 'Brr Villa Alegria Cll 49 # 40A 58',
//         representante: 'YULIENIS LOPEZ MORENO',
//         logo: 'DirVerde_Images/25.Logo.024252.jpg',
//         pos_gps: null,
//         id_fase: 1,
//         estado: 'Activo',
//         id_municipio: 13001,
//       },
//       {
//         negocio: 'GRANJA ECOSIBAR S.A.S.',
//         id_grupo: 2,
//         sub_categoria: 'TURISMO SOSTENIBLE',
//         descripcion: 'Granja dedicada al agroturismo y la educación ambiental.',
//         actividad: 'Agroturismo y granja sostenible',
//         direccion: 'Vereda Turquia',
//         representante: 'ALFREDO VILLADIEGO',
//         logo: 'DirVerde_Images/26.Logo.020058.jpg',
//         url_youtube: 'https://www.youtube.com/@granjaecosibar1634',
//         pos_gps: '-75.1185706,9.8469019',
//         id_fase: 1,
//         estado: 'Activo',
//         id_municipio: 13001,
//       },
//       {
//         negocio: 'SACHA BOLÍVAR ORGÁNICA S.A.S',
//         id_grupo: 2,
//         sub_categoria: 'AGROINDUSTRIA SOSTENIBLE',
//         descripcion: 'Producción de esencias y perfumes naturales a partir de cultivos orgánicos.',
//         actividad: 'Esencias naturales',
//         direccion: 'Barrio Villa María Calle 45 # 21 -48',
//         representante: 'OSCAR ARIZA MARTÍNEZ',
//         logo: 'DirVerde_Images/30.Logo.020532.jpg',
//         pos_gps: '-75.1272618,9.8285524',
//         id_fase: 1,
//         estado: 'Activo',
//         id_municipio: 13001,
//       },
//       {
//         negocio: 'VINO ARTESANAL NATUUR',
//         id_grupo: 2,
//         sub_categoria: 'AGROINDUSTRIA SOSTENIBLE',
//         descripcion: 'Producción de vinos artesanales a partir de frutas tropicales de la región.',
//         actividad: 'Vinicultura artesanal',
//         direccion: 'Calle 13 #12-09 Barrio Arriba',
//         representante: 'HECTOR LUIS MEDRANO SANCHEZ',
//         logo: 'DirVerde_Images/32.Logo.020407.jpg',
//         url_instagram: 'https://www.instagram.com/vinonatuur/',
//         pos_gps: '-75.7762061,10.4485786',
//         id_fase: 1,
//         estado: 'Activo',
//         id_municipio: 13001,
//       },
//       {
//         negocio: 'ASOGAÑAFROSAN',
//         id_grupo: 2,
//         sub_categoria: 'AGROINDUSTRIA SOSTENIBLE',
//         descripcion:
//           'Asociación dedicada a la transformación de ñame afro en diversos derivados alimenticios.',
//         actividad: 'Transformación de ñame',
//         direccion: 'Br Las Canteras, San Cayetano',
//         representante: 'DENIS DEL CARMEN CAMARGO',
//         logo: 'DirVerde_Images/33.Logo.022005.jpg',
//         pos_gps: '-75.1412789,10.0820767',
//         id_fase: 1,
//         estado: 'Activo',
//         id_municipio: 13001,
//       },
//       {
//         negocio: 'AGRÍCOLA CAMELIAS S.A.S',
//         id_grupo: 2,
//         sub_categoria: 'TURISMO SOSTENIBLE',
//         descripcion:
//           'Producción de miel de abeja, huevos orgánicos y oferta de servicios de agroturismo.',
//         actividad: 'Apicultura y Agroturismo',
//         direccion: 'Camino Los Volcanes KM 1.5',
//         representante: 'RAFAEL ERNESTO CAMACHO ELIAS',
//         logo: 'DirVerde_Images/38.Logo.232534.jpg',
//         url_facebook: 'https://www.facebook.com/agricolacamelias/',
//         pos_gps: '-75.3810127,10.3324401',
//         id_fase: 1,
//         estado: 'Activo',
//         id_municipio: 13001,
//       },
//       {
//         negocio: 'VINOS JHOSEMAR',
//         id_grupo: 2,
//         sub_categoria: 'AGROINDUSTRIA SOSTENIBLE',
//         descripcion: 'Venta de aperitivos y vinos artesanales elaborados con frutas tropicales.',
//         actividad: 'Aperitivos de frutas artesanales',
//         direccion: 'Urb Bajo Miranda Mz 3 Lt 42',
//         representante: 'ARLENIS VARGAS PÉREZ',
//         logo: 'DirVerde_Images/41.Logo.232636.jpg',
//         url_instagram: 'https://www.instagram.com/vinosjhosemar/',
//         pos_gps: '-75.4573793,10.3744539',
//         id_fase: 1,
//         estado: 'Activo',
//         id_municipio: 13001,
//       },
//       {
//         negocio: 'ASOCIACIÓN RENACER DEL CAMPO',
//         id_grupo: 2,
//         sub_categoria: 'AGROINDUSTRIA SOSTENIBLE',
//         descripcion: 'Transformación de yuca en productos lácteos como malteadas y yogurt natural.',
//         actividad: 'Lácteos derivados de yuca',
//         direccion: 'Brr San Sebastian Cra 18, Zambrano',
//         representante: 'NICOL DANIELA QUIROZ OROZCO',
//         logo: 'DirVerde_Images/44.Logo.211517.jpg',
//         url_facebook: 'https://www.facebook.com/RenacerDelCampoZamBol/',
//         pos_gps: null,
//         id_fase: 1,
//         estado: 'Activo',
//         id_municipio: 13001,
//       },
//       {
//         negocio: 'ASOMUPROR',
//         id_grupo: 2,
//         sub_categoria: 'AGROINDUSTRIA SOSTENIBLE',
//         descripcion:
//           'Producción de dulces típicos derivados de frutas locales por mujeres del río.',
//         actividad: 'Producción de dulces artesanales',
//         direccion: 'Finca Luz Mel, Zambrano',
//         representante: 'CRISTINA ISABEL SANTANA HERNANDEZ',
//         logo: 'DirVerde_Images/47.Logo.145840.png',
//         pos_gps: null,
//         id_fase: 1,
//         estado: 'Verificado',
//         id_municipio: 13001,
//       },
//     ],
//     skipDuplicates: true,
//   });
// }

// dir_verde_resto()
